[versions]
loom = "1.10.+"
githubRelease = "2.4.1"
minotaur = "2.+"
curse = "1.1.+"

mc = "1.21.1"
fl = "0.16.14"
yarn = "1.21.1+build.3"
fapi = "0.116.7+1.21.1"

surveyor = "1.0.0-alpha.14+1.21"
blaystones = "21.1.24+fabric-1.21.1"
balm = "21.0.55+fabric-1.21.1"
fwaystones = "3.3.4+mc1.21.1"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
curse = { id = "net.darkhax.curseforgegradle", version.ref = "curse" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }

surveyor = { group = "folk.sisby", name = "surveyor", version.ref = "surveyor" }
balm = { group = "maven.modrinth", name = "balm", version.ref = "balm" }
blaystones = { group = "maven.modrinth", name = "waystones", version.ref = "blaystones" }
fwaystones = { group = "maven.modrinth", name = "fwaystones", version.ref = "fwaystones" }
