[versions]
loom = "1.13.+"
githubRelease = "2.4.1"
minotaur = "2.+"
curse = "1.1.+"

mc = "1.20.1"
fl = "0.16.14"
yarn = "1.20.1+build.10"
fapi = "0.92.2+1.20.1"

surveyor = "1.0.0+1.20"
blaystones = "14.1.17+fabric-1.20.1"
balm = "7.3.37+fabric-1.20.1"
fwaystones = "3.3.3+mc1.20.1"


[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
curse = { id = "net.darkhax.curseforgegradle", version.ref = "curse" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }

surveyor = { group = "folk.sisby", name = "surveyor", version.ref = "surveyor" }
balm = { group = "maven.modrinth", name = "balm", version.ref = "balm" }
blaystones = { group = "maven.modrinth", name = "waystones", version.ref = "blaystones" }
fwaystones = { group = "maven.modrinth", name = "fwaystones", version.ref = "fwaystones" }
